### ISSUE TITLE
命令报错

### ISSUE THREAD

**Issue by AimLuo** [forsigner/dahlia#10]
@oclif依赖缺失，

**Comment by AimLuo** [comment]
![image](https://user-images.githubusercontent.com/21124342/59562660-ce5dec00-9061-11e9-8be4-e6bbeb8df778.png)
node 10.16.0 通过nvm安装，
yarn 1.16.0 通过官方msi文件安装。

以下为报错信息
`λ dh new dh-app
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@oclif/command'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\aimluo\AppData\Local\Yarn\Data\global\node_modules\dahlia-cli\bin\run:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by AimLuo** [comment]
cli为毛删了。。

**Comment by forsigner** [comment]
@AimLuo 发现最新版本 react-scripts不能全局安装使用，所以 dahlia 改成和 create-react-app 一致的使用方式：

```bash
npx create-dahlia-app myapp
cd myapp
npm start
```
## 几种初始化应用方式

### 使用 npx

```bash
npx create-dahlia-app myapp
```

## 使用 npm

```bash
npm init dahlia-app myapp
```

## 使用 yarn

```bash
yarn create dahlia-app myapp
```

## 全局安装

```bash
yarn global add create-dahlia-app
create-dahlia-app myapp
```

## 可用脚本

- `npm start` - 启动开发服务器
- `npm test` - 启动单元测试
- `npm build` - 生产环境打包

**Comment by AimLuo** [comment]
--
